// Auto-tune wizard. Steps: intro → silence → normal → loud → review.
// Stepper at the top, circular countdown during capture, recommendations
// at review.

import { useEffect, useRef, useState } from 'react';
import { Check, ChevronRight, Sparkles } from 'lucide-react';

import {
  recordingStart,
  recordingStop,
  recordingDiscard,
  type RecordingHandle,
} from '../../ipc/recording';
import { wizardAnalyze, wizardSynthesize, type PhaseStats } from '../../ipc/wizard';
import { profileSave } from '../../ipc/profiles';
import { useAppStore } from '../../state/useAppStore';

type Step = 'intro' | 'silence' | 'normal' | 'loud' | 'analyzing' | 'review' | 'saved';

interface PhaseDef {
  id: 'silence' | 'normal' | 'loud';
  label: string;
  prompt: string;
  durationMs: number;
}

const PHASES: PhaseDef[] = [
  {
    id: 'silence',
    label: 'Silence',
    prompt: "Stay quiet for five seconds. We're measuring your room.",
    durationMs: 5_000,
  },
  {
    id: 'normal',
    label: 'Normal',
    prompt: 'Speak as you normally would — a sentence at your natural volume.',
    durationMs: 8_000,
  },
  {
    id: 'loud',
    label: 'Loud',
    prompt: "Now something louder, like you're excited or laughing.",
    durationMs: 4_000,
  },
];

const STEPPER = ['Intro', 'Silence', 'Normal', 'Loud', 'Review'] as const;

interface Props {
  open: boolean;
  onClose: () => void;
}

export function AutoTuneWizard({ open, onClose }: Props) {
  const engineRunning = useAppStore((s) => s.engine.status === 'running');
  const setActiveProfile = useAppStore((s) => s.setActiveProfile);
  const [step, setStep] = useState<Step>('intro');
  const [elapsedMs, setElapsedMs] = useState(0);
  const [stats, setStats] = useState<Record<'silence' | 'normal' | 'loud', PhaseStats | null>>({
    silence: null,
    normal: null,
    loud: null,
  });
  const [recs, setRecs] = useState<string[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [profileName, setProfileName] = useState('Auto-tune');
  const tickRef = useRef<number | null>(null);

  useEffect(() => {
    if (!open) return;
    setStep('intro');
    setStats({ silence: null, normal: null, loud: null });
    setRecs(null);
    setError(null);
    setProfileName('Auto-tune');
    setElapsedMs(0);
  }, [open]);

  useEffect(() => {
    return () => {
      if (tickRef.current !== null) window.clearInterval(tickRef.current);
    };
  }, []);

  const runPhase = async (def: PhaseDef) => {
    setError(null);
    setElapsedMs(0);
    setStep(def.id);
    try {
      const h = await recordingStart();
      const startTs = performance.now();
      tickRef.current = window.setInterval(() => {
        const el = performance.now() - startTs;
        setElapsedMs(el);
        if (el >= def.durationMs) {
          if (tickRef.current !== null) {
            window.clearInterval(tickRef.current);
            tickRef.current = null;
          }
          finishPhase(def, h);
        }
      }, 80);
    } catch (e) {
      setError(String(e));
      setStep('intro');
    }
  };

  const finishPhase = async (def: PhaseDef, h: RecordingHandle) => {
    try {
      const stopped = await recordingStop();
      const rawPath = (stopped ?? h).raw_path;
      const s = await wizardAnalyze(rawPath);
      try {
        await recordingDiscard(rawPath);
      } catch (err) {
        console.warn(err);
      }
      const next = { ...stats, [def.id]: s };
      setStats(next);
      if (def.id === 'silence') await runPhase(PHASES[1]!);
      else if (def.id === 'normal') await runPhase(PHASES[2]!);
      else {
        setStep('analyzing');
        if (next.silence && next.normal && next.loud) {
          try {
            const result = await wizardSynthesize(next.silence, next.normal, next.loud);
            setRecs(result.recommendations);
            useAppStore.getState().setModules(result.modules);
            setStep('review');
          } catch (err) {
            setError(String(err));
            setStep('intro');
          }
        }
      }
    } catch (e) {
      setError(String(e));
      setStep('intro');
    }
  };

  const startWizard = async () => {
    if (!engineRunning) {
      setError('Start the audio engine on the Dashboard first.');
      return;
    }
    await runPhase(PHASES[0]!);
  };

  const saveProfile = async () => {
    const name = profileName.trim() || 'Auto-tune';
    const modules = useAppStore.getState().modules;
    const profile = {
      schemaVersion: 1 as const,
      id: crypto.randomUUID(),
      name,
      kind: 'user' as const,
      author: 'Auto-tune',
      notes: 'Generated by MicLayer auto-tune.',
      modules,
    };
    try {
      const saved = await profileSave(profile);
      setActiveProfile(saved);
      setStep('saved');
    } catch (e) {
      setError(String(e));
    }
  };

  if (!open) return null;

  const stepIdx =
    step === 'intro'
      ? 0
      : step === 'silence'
        ? 1
        : step === 'normal'
          ? 2
          : step === 'loud'
            ? 3
            : 4;

  const activePhase = PHASES.find((p) => p.id === step);

  return (
    <div className="ml-scrim" role="dialog" aria-modal="true">
      <div className="ml-modal" style={{ maxWidth: 640 }}>
        <div className="ml-modal-head">
          <Stepper currentIdx={stepIdx} />
          {step === 'intro' && (
            <>
              <div className="ml-modal-title">Let's listen to your room.</div>
              <div className="ml-modal-sub">
                Three short captures — silence, normal speech, loud speech — then we'll suggest a
                starting point in plain English. The audio stays on your computer.
              </div>
            </>
          )}
          {step === 'silence' && (
            <>
              <div className="ml-modal-title">Stay quiet for five seconds.</div>
              <div className="ml-modal-sub">Don't hold your breath.</div>
            </>
          )}
          {step === 'normal' && (
            <>
              <div className="ml-modal-title">Speak normally for eight seconds.</div>
              <div className="ml-modal-sub">Read a sentence or two at your natural volume.</div>
            </>
          )}
          {step === 'loud' && (
            <>
              <div className="ml-modal-title">Now something louder.</div>
              <div className="ml-modal-sub">
                Speak as if you're excited or laughing. We'll set the limiter to keep your peaks
                polite.
              </div>
            </>
          )}
          {step === 'analyzing' && (
            <>
              <div className="ml-modal-title">One moment…</div>
              <div className="ml-modal-sub">Analyzing the three samples.</div>
            </>
          )}
          {step === 'review' && (
            <>
              <div className="ml-modal-title">Here's what we heard.</div>
              <div className="ml-modal-sub">
                Save as a new profile and try it. You can always re-run later.
              </div>
            </>
          )}
          {step === 'saved' && (
            <>
              <div className="ml-modal-title">Saved.</div>
              <div className="ml-modal-sub">Your new profile is active.</div>
            </>
          )}
        </div>

        <div className="ml-modal-body">
          {error && (
            <p
              style={{
                marginBottom: 10,
                fontSize: 12,
                color: 'var(--ml-bad)',
                background: 'color-mix(in oklch, var(--ml-bad) 8%, transparent)',
                border: '1px solid color-mix(in oklch, var(--ml-bad) 30%, transparent)',
                borderRadius: 'var(--ml-r-md)',
                padding: '10px 12px',
              }}
            >
              {error}
            </p>
          )}

          {step === 'intro' && (
            <ul
              style={{
                listStyle: 'none',
                padding: 0,
                margin: 0,
                display: 'flex',
                flexDirection: 'column',
                gap: 8,
              }}
            >
              {[
                'About 20 seconds total.',
                "Stay where you'll be when you actually use MicLayer.",
                "Headphones recommended so playback doesn't bleed into the mic.",
              ].map((s, i) => (
                <li
                  key={i}
                  style={{
                    display: 'flex',
                    alignItems: 'flex-start',
                    gap: 10,
                    fontSize: 12.5,
                  }}
                >
                  <Check size={14} style={{ color: 'var(--ml-accent)', marginTop: 1 }} />
                  <span>{s}</span>
                </li>
              ))}
            </ul>
          )}

          {activePhase && (
            <CaptureBlock
              phase={activePhase}
              elapsedMs={elapsedMs}
            />
          )}

          {step === 'analyzing' && (
            <p style={{ fontSize: 12, color: 'var(--ml-fg-muted)' }}>Analyzing…</p>
          )}

          {step === 'review' && recs && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {recs.map((r, i) => (
                <div
                  key={i}
                  style={{
                    display: 'flex',
                    gap: 12,
                    alignItems: 'flex-start',
                    padding: '10px 12px',
                    background: 'var(--ml-surface-2)',
                    border: '1px solid var(--ml-border)',
                    borderRadius: 'var(--ml-r-md)',
                  }}
                >
                  <Check size={14} style={{ color: 'var(--ml-good)', marginTop: 2 }} />
                  <span style={{ fontSize: 12.5 }}>{r}</span>
                </div>
              ))}
              <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 4 }}>
                <input
                  value={profileName}
                  onChange={(e) => setProfileName(e.target.value)}
                  className="ml-input"
                  placeholder="Name for the new profile"
                />
              </div>
            </div>
          )}

          {step === 'saved' && (
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                fontSize: 13,
              }}
            >
              <Sparkles size={16} style={{ color: 'var(--ml-accent)' }} />
              Your new profile is active.
            </div>
          )}
        </div>

        <div className="ml-modal-foot">
          {step === 'intro' && (
            <>
              <button type="button" className="ml-btn ghost" onClick={onClose}>
                Skip
              </button>
              <button type="button" className="ml-btn primary" onClick={startWizard}>
                Begin <ChevronRight size={12} />
              </button>
            </>
          )}
          {(step === 'silence' || step === 'normal' || step === 'loud') && (
            <>
              <button type="button" className="ml-btn ghost" onClick={onClose}>
                Cancel
              </button>
              <button type="button" className="ml-btn" disabled>
                Listening…
              </button>
            </>
          )}
          {step === 'analyzing' && (
            <button type="button" className="ml-btn ghost" disabled>
              Working…
            </button>
          )}
          {step === 'review' && (
            <>
              <button type="button" className="ml-btn ghost" onClick={() => setStep('intro')}>
                Re-run
              </button>
              <button type="button" className="ml-btn primary" onClick={saveProfile}>
                Save as profile <ChevronRight size={12} />
              </button>
            </>
          )}
          {step === 'saved' && (
            <button type="button" className="ml-btn primary" onClick={onClose}>
              Done
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

function Stepper({ currentIdx }: { currentIdx: number }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
      {STEPPER.map((label, i) => {
        const isCurrent = i === currentIdx;
        const isDone = i < currentIdx;
        const dotBg = isCurrent
          ? 'var(--ml-accent)'
          : isDone
            ? 'color-mix(in oklch, var(--ml-good) 18%, transparent)'
            : 'var(--ml-surface-2)';
        const border = isCurrent
          ? 'transparent'
          : isDone
            ? 'color-mix(in oklch, var(--ml-good) 35%, transparent)'
            : 'var(--ml-border)';
        return (
          <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 6,
                color: isCurrent ? 'var(--ml-fg)' : isDone ? 'var(--ml-good)' : 'var(--ml-fg-faint)',
              }}
            >
              <span
                style={{
                  width: 18,
                  height: 18,
                  borderRadius: '50%',
                  background: dotBg,
                  border: `1px solid ${border}`,
                  fontSize: 9.5,
                  fontWeight: 600,
                  color: isCurrent ? 'var(--ml-accent-fg)' : 'currentColor',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                {isDone ? '✓' : i + 1}
              </span>
              <span style={{ fontSize: 11, fontWeight: 500 }}>{label}</span>
            </div>
            {i < STEPPER.length - 1 && (
              <span style={{ width: 12, height: 1, background: 'var(--ml-border)' }} />
            )}
          </div>
        );
      })}
    </div>
  );
}

function CaptureBlock({ phase, elapsedMs }: { phase: PhaseDef; elapsedMs: number }) {
  const elapsedS = elapsedMs / 1000;
  const totalS = phase.durationMs / 1000;
  const remaining = Math.max(0, totalS - elapsedS);
  const radius = 48;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference * (1 - elapsedS / totalS);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 18, marginTop: 6 }}>
      <p style={{ fontSize: 12.5, color: 'var(--ml-fg)', textAlign: 'center' }}>{phase.prompt}</p>
      <div
        style={{
          position: 'relative',
          margin: '0 auto',
          width: 110,
          height: 110,
          borderRadius: '50%',
          background: 'var(--ml-surface-2)',
          border: '1px solid var(--ml-border)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <svg width="110" height="110" viewBox="0 0 110 110" style={{ position: 'absolute' }}>
          <circle
            cx="55"
            cy="55"
            r={radius}
            fill="none"
            stroke="var(--ml-accent)"
            strokeWidth="3"
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap="round"
            transform="rotate(-90 55 55)"
            style={{ transition: 'stroke-dashoffset 80ms linear' }}
          />
        </svg>
        <div className="ml-mono" style={{ fontSize: 26, fontWeight: 500 }}>
          {remaining.toFixed(1)}s
        </div>
      </div>
    </div>
  );
}
